version: '3.3'
services:
  rabbitmq:
      image: rabbitmq:3-management
      environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: nimda
      ports:
        - '15672:15672'
        - '5672:5672'