version: '2'
services:
  apache-camel-spring-boot:
      build: .
      depends_on:
        - rabbitmq
      command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "java", "-jar", "apache-camel-spring-boot.jar"]
      volumes:
        - ./files:/home/application/apache-camel-spring-boot/files
  rabbitmq:
      image: rabbitmq:3-management
      environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: nimda
      ports:
        - '15672:15672'
        - '5672:5672'