spring:
  data:
    mongodb:
      host:
      database:
      username:
      password:

server:
  port: 9000

rabbitmq:
  host:
  port:
  username:
  password:
  autoDelete:
  deliveryMode:
    producerExchange:
      name:
      producerQueue:
        name:
        routingKey:
        active: true
    consumerExchange:
      name:
        consumerQueue:
          name:
          routingKey:
          active: true