server:
  port: 9000

rabbitmq:
  host: rabbitmq
  port: 5672
  username: admin
  password: nimda
  producerExchange:
    name: EX_PRODUCER
    producerPath: /home/application/apache-camel-spring-boot/files
    producerQueue:
      name: QU_PRODUCER
      routingKey: RK_PRODUCER
  consumerExchange:
    name: EX_CONSUMER
    consumerQueue:
      name: QU_CONSUMER
      routingKey: RK_CONSUMER